//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internal_set_a.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDonor
    {
        public int ID_PK { get; set; }
        public string Name { get; set; }
        public System.DateTime Donation_Date { get; set; }
        public string City { get; set; }
        public string Aadhar_Number { get; set; }
        public int Donation_Amount { get; set; }
    }
}
